---
title: "First Knit"
author: "Joel Calderin"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
  
I went to High School and graduated in 2023 at Acceleration Academy in Las Vegas, Nevada. All of my classes were online. English is easier for me. My best subject was English because I enjoyed to write.
     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
I am not on a laptop but I am on an Apple Ipad. I would say I'm at about a 7 with my understanding on computers. My connection is good where I live.
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     

My full name is Joel Calderin Serrano but I prefer to go by Joel Calderin. I am okay with people calling me by my first name.
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
I want to go as far as I can with baseball. I am at AVC to play baseball with goals to get a scholarship to a 4 year school. If that fails, I am studying psychology in hopes to become a therapist.
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
No I have not gone to foreign countries. I don't have any plans or wants to go out of the country. I have never been in the military but if I did I would go into the Navy.This is because my brother is currently in the Navy.
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
I have never taken math 115 or 116. I did not know that information before. I want to attain an A or a B for this class. This is not a requirement for my future plans but it is a goal of mine. My plan is to go as far as I can with baseball, and if that fails then I want to become a psychologist/therapist. 
   
 






  




